"""Text for the "How it works" page (/<lang>/how-it-works/). Rendered by build.py."""

HOW = {
    "en-us": {
        "nav": "How it works",
        "title": "How Storia works",
        "kicker": "Architecture",
        "lede": "Storia is four programs that work together. Only the server is required; the others add a network, "
                "more CPU for terrain, or both. This page explains what each one does, where it runs and what travels between them.",
        "diagram_label": "Overview of a full Storia network",
        "diagram_desc": [
            "Players connect to Storia Proxy, which listens on port 25565.",
            "Storia Proxy forwards each player to one of the Storia servers (for example lobby and survival), using modern forwarding.",
            "A Storia server connects to Storia Relay, which listens on port 25590, and sends it terrain work, encrypted.",
            "Storia Relay hands each piece of work to one of the Storia Workers, which send the terrain back the same way.",
        ],
        "d": {"players": "Players", "proxy": "Storia Proxy", "lobby": "Storia · lobby", "survival": "Storia · survival",
              "relay": "Storia Relay", "worker": "Worker", "net": "Network", "game": "Game servers", "help": "Terrain helpers",
              "mc": "Minecraft · 25565", "fwd": "modern forwarding", "enc": "encrypted · 25590", "wsub": "terrain noise"},
        "roles_t": "The four programs",
        "roles_p": "Each program has one job. Together they form a network where no single busy place can slow everyone down.",
        "roles": {
            "storia": {
                "role": "The game server",
                "does": "Runs the world: players, mobs, redstone, farms, chunks. Built on Folia, so different areas of the world tick on different CPU cores.",
                "not": "Does not need the other three. On its own it is a complete Minecraft server.",
                "runs": "Your main machine (or one per game mode behind a proxy).",
                "needs": "Java 25, RAM for the world (RAM world) plus the heap.",
                "ports": "25565 for players (or a private port behind the proxy).",
                "config": "storia.yml, plus the usual Paper and Folia files.",
                "docs": "getting-started",
            },
            "proxy": {
                "role": "The front door",
                "does": "Accepts every player on one address and sends them to the right server. Shows the server list MOTD, a live tab list and network-wide join and switch messages, built from 50 placeholders.",
                "not": "Does not run any world, so it needs very little CPU. Plugins for it are Velocity plugins.",
                "runs": "Any small machine, often next to the servers.",
                "needs": "Java 21+, about 512 MB of RAM.",
                "ports": "25565 for players.",
                "config": "velocity.toml, storia-proxy.toml.",
                "docs": "proxy",
            },
            "worker": {
                "role": "Extra CPU for terrain",
                "does": "Computes the heaviest step of terrain generation (the shape of the land, caves and aquifers) for a Storia server, and sends the result back.",
                "not": "Opens no player port, never stores or changes your world, never sees players, chat or inventories.",
                "runs": "Any spare machine: an old PC, a second server, a cloud VM.",
                "needs": "Java 25, a copy of the world folder without its chunks (level.dat, datapacks, data).",
                "ports": "25590 when listening; none when it connects out to a relay.",
                "config": "storia.yml (offload.mode: worker).",
                "docs": "worker",
            },
            "relay": {
                "role": "The dispatcher",
                "does": "Sits between servers and workers and hands each piece of terrain work to the least busy worker whose terrain matches exactly. Workers can join and leave at any time.",
                "not": "Does no terrain work itself and needs no Minecraft files.",
                "runs": "One reachable machine; can be the proxy's machine.",
                "needs": "Java 21+, about 256 MB of RAM.",
                "ports": "25590 for servers and workers.",
                "config": "relay.properties.",
                "docs": "relay",
            },
        },
        "labels": {"does": "What it does", "not": "What it does not do", "runs": "Runs on", "needs": "Needs", "ports": "Ports", "config": "Configuration", "docs": "Read the docs"},
        "inside_t": "Inside the Storia server",
        "inside_p": "The server is where the world lives. These layers work together to keep every player's experience smooth.",
        "inside": [
            ("Regions", "Folia groups nearby chunks into regions. Each region ticks on its own CPU core, so a busy base on one side of the world does not slow down a player on the other side.", "introduction"),
            ("Tick guard", "When a region gets too slow, mobs in crowded chunks think less often. Players standing there are not limited, and redstone is never touched.", "tick-guard"),
            ("Player budget", "Only players who add load by themselves, such as flying fast with elytra, get a shorter view distance while their region is busy.", "player-budget"),
            ("RAM world", "Worlds live in RAM and are written to disk in the background, so saving and loading chunks never waits for the disk.", "ram-world"),
            ("Pregeneration", "Generates terrain ahead of time using every spare core, so exploring only loads chunks that already exist.", "pregeneration"),
            ("Offload client", "Sends the noise step of new chunks to workers, and generates locally whenever a worker is busy, slow or gone.", "offload"),
        ],
        "chunk_t": "The journey of a new chunk",
        "chunk_p": "What happens when a player walks into land that has never been generated, with a relay and workers set up.",
        "chunk": [
            ("server", "A player reaches the edge of the generated world. The server needs new chunks."),
            ("server", "The server places structure starts and biomes. These depend on the whole world, so they stay local."),
            ("server", "For the noise step, it picks a connection with free capacity and sends a request: the chunk position, the dimension and the outlines of nearby structures."),
            ("relay", "The relay forwards the request to the least busy worker that produced identical probe chunks for this dimension."),
            ("worker", "The worker computes the terrain shape, caves and aquifers, and sends back the blocks and heightmaps."),
            ("server", "The server checks the answer and applies it. If no answer arrives in time, it generates the chunk itself instead."),
            ("server", "The server adds surface blocks, caves, trees, ores and light, then sends the finished chunk to the player."),
        ],
        "who": {"server": "Storia server", "relay": "Storia Relay", "worker": "Storia Worker"},
        "join_t": "The journey of a player",
        "join": [
            ("Server list", "The player's client pings the proxy's address. Storia Proxy answers with the MOTD from storia-proxy.toml, with placeholders such as {online} filled in."),
            ("Login", "The proxy authenticates the player with Mojang, then connects them to the first server in its try list."),
            ("Forwarding", "Modern forwarding passes the player's UUID and skin to the Storia server, signed with the forwarding secret, so the server can trust it."),
            ("Playing", "The tab list refreshes every second with placeholders about the player and the network. Join, leave and switch messages go to everyone."),
            ("Switching", "When the player moves to another server, the proxy keeps the connection and moves it. If a server stops unexpectedly, the proxy sends its players to another one."),
        ],
        "wire_t": "What travels over each connection",
        "wire_h": ["Connection", "Carries", "Protection"],
        "wire": [
            ("Player ↔ Storia Proxy", "The Minecraft protocol: movement, chat, chunks, everything the game needs.", "Minecraft's own encryption (online mode)."),
            ("Storia Proxy ↔ Storia server", "The same Minecraft traffic, plus the forwarded player identity.", "Signed with the forwarding secret. Keep servers off the public internet."),
            ("Storia server ↔ Relay or Worker", "Chunk positions, the dimension and nearby structure outlines one way; terrain blocks and heightmaps the other. Never players, chat or inventories.", "AES-256-GCM with keys derived from your shared secret, which is never sent."),
            ("Relay ↔ Worker", "The same terrain requests and answers, passed through.", "The same encryption, with its own keys per connection."),
        ],
        "fail_t": "When something stops",
        "fail_h": ["If this stops", "What happens"],
        "fail": [
            ("A worker", "Its unfinished requests go to another worker, or back to the server, which generates those chunks itself. At most, those chunks take a moment longer."),
            ("The relay", "Servers generate all terrain locally and reconnect automatically when the relay is back."),
            ("A Storia server", "The proxy moves its players to another server in the try list. The other servers keep running."),
            ("The proxy", "Players cannot join through it until it is back. Servers and their worlds keep running and nothing is lost."),
            ("The machine running a server", "With the RAM world, changes since the last sync (5 minutes by default) are lost; if only the server process dies, the RAM copy is recovered on the next start."),
        ],
        "setups_t": "Four common setups",
        "setups_p": "Start with the first one and add programs as your server grows. Nothing needs to be reinstalled.",
        "setups": [
            ("Single server", "For most servers. Everything on one machine.", ["players", "storia"], "Storia only"),
            ("Network", "Several game modes behind one address, with a shared tab list and messages.", ["players", "proxy", "storia×2"], "Storia Proxy + Storia"),
            ("Server with helpers", "A busy exploration or pregeneration server with one or two spare machines.", ["players", "storia", "worker×2"], "Storia + Storia Worker"),
            ("Full network", "Many servers sharing a pool of workers that can come and go.", ["players", "proxy", "storia×3", "relay", "worker×N"], "all four"),
        ],
        "chips": {"players": "Players", "proxy": "Proxy", "storia": "Storia", "worker": "Worker", "relay": "Relay"},
        "req_t": "Requirements at a glance",
        "req_h": ["Program", "Java", "Memory", "Port", "Files it needs"],
        "req": [
            ("Storia", "25", "Heap + the world in RAM", "25565", "The world"),
            ("Storia Proxy", "21+", "~512 MB", "25565", "None"),
            ("Storia Worker", "25", "2–4 GB", "25590 (or none with a relay)", "The world folder without region, entities, poi"),
            ("Storia Relay", "21+", "~256 MB", "25590", "None"),
        ],
        "req_note": "Every port can be changed. All four programs come in every release on the downloads page.",
        "cta": "Download all four",
    },
    "ja-jp": {
        "nav": "仕組み",
        "title": "Storia の仕組み",
        "kicker": "Architecture",
        "lede": "Storia は、連携して動く 4 つのソフトでできています。必須なのはサーバーだけで、ほかのソフトはネットワーク化や、"
                "地形生成のための CPU の追加、またはその両方のために使います。このページでは、それぞれの役割、動かす場所、やり取りする内容を説明します。",
        "diagram_label": "Storia のネットワーク全体の構成図",
        "diagram_desc": [
            "プレイヤーは、Storia Proxy（ポート 25565 で待ち受け）に接続します。",
            "Storia Proxy は、modern フォワーディングを使って、各プレイヤーを Storia サーバー（たとえばロビーとサバイバル）のどれかに送ります。",
            "Storia サーバーは、Storia Relay（ポート 25590 で待ち受け）に接続し、地形生成の仕事を暗号化して送ります。",
            "Storia Relay は仕事を Storia Worker のどれかに渡し、ワーカーは同じ経路で地形を返します。",
        ],
        "d": {"players": "Players", "proxy": "Storia Proxy", "lobby": "Storia · lobby", "survival": "Storia · survival",
              "relay": "Storia Relay", "worker": "Worker", "net": "Network", "game": "Game servers", "help": "Terrain helpers",
              "mc": "Minecraft · 25565", "fwd": "modern forwarding", "enc": "encrypted · 25590", "wsub": "terrain noise"},
        "roles_t": "4 つのソフト",
        "roles_p": "ソフトごとに役割は 1 つです。組み合わせると、1 か所の重さが全員の足を引っ張らないネットワークになります。",
        "roles": {
            "storia": {
                "role": "ゲームサーバー",
                "does": "ワールドを動かします。プレイヤー、モブ、回路、トラップ、チャンクのすべてです。Folia ベースなので、ワールドの場所ごとに別々の CPU コアで処理します。",
                "not": "ほかの 3 つは必要ありません。単体で完全な Minecraft サーバーです。",
                "runs": "メインのマシン（プロキシを使うなら、ゲームモードごとに 1 台ずつ）。",
                "needs": "Java 25。RAM ワールドのためのワールド分の RAM と、ヒープ。",
                "ports": "プレイヤー用の 25565（プロキシの裏に置くなら非公開のポート）。",
                "config": "storia.yml と、いつもの Paper・Folia の設定ファイル。",
                "docs": "getting-started",
            },
            "proxy": {
                "role": "玄関",
                "does": "すべてのプレイヤーを 1 つのアドレスで受け付け、適切なサーバーに送ります。サーバーリストの MOTD、自動更新のタブリスト、ネットワーク全体の参加・移動メッセージを、50 個のプレースホルダーで表示します。",
                "not": "ワールドは動かさないので、CPU はほとんど使いません。プラグインは Velocity 用のものです。",
                "runs": "小さなマシンで十分。サーバーと同じマシンに置くことも多いです。",
                "needs": "Java 21 以上、RAM 512 MB ほど。",
                "ports": "プレイヤー用の 25565。",
                "config": "velocity.toml、storia-proxy.toml。",
                "docs": "proxy",
            },
            "worker": {
                "role": "地形生成のための追加の CPU",
                "does": "地形生成で一番重い処理（土地の形・洞窟・帯水層）を Storia サーバーの代わりに計算し、結果を返します。",
                "not": "プレイヤー用ポートは開かず、ワールドを保存・変更することもなく、プレイヤー・チャット・インベントリを見ることもありません。",
                "runs": "空いているマシンならどこでも。古い PC、2 台目のサーバー、クラウドの VM など。",
                "needs": "Java 25、チャンクを除いたワールドフォルダのコピー（level.dat・データパック・data）。",
                "ports": "待ち受けるなら 25590。リレーに自分から接続するなら不要。",
                "config": "storia.yml（offload.mode: worker）。",
                "docs": "worker",
            },
            "relay": {
                "role": "仕事の配り役",
                "does": "サーバーとワーカーの間に入り、地形生成の仕事を、地形が完全に一致するワーカーのうち一番空いているものに渡します。ワーカーはいつでも追加・削除できます。",
                "not": "自分では地形を計算せず、Minecraft のファイルも不要です。",
                "runs": "サーバーとワーカーの両方から届くマシン 1 台。プロキシと同じマシンでも構いません。",
                "needs": "Java 21 以上、RAM 256 MB ほど。",
                "ports": "サーバーとワーカー用の 25590。",
                "config": "relay.properties。",
                "docs": "relay",
            },
        },
        "labels": {"does": "すること", "not": "しないこと", "runs": "動かす場所", "needs": "必要なもの", "ports": "ポート", "config": "設定ファイル", "docs": "ドキュメントを読む"},
        "inside_t": "Storia サーバーの中身",
        "inside_p": "ワールドがあるのはサーバーです。次の仕組みが連携して、プレイヤー全員の快適さを保ちます。",
        "inside": [
            ("リージョン", "Folia は近くのチャンクをリージョンにまとめ、リージョンごとに別々の CPU コアで処理します。ワールドの片側の重い拠点が、反対側のプレイヤーを遅くすることはありません。", "introduction"),
            ("Tick Guard", "リージョンが重くなりすぎると、密集チャンクのモブの判断の回数を減らします。そこにいるプレイヤーは制限されず、回路にも触れません。", "tick-guard"),
            ("プレイヤーごとの予算", "エリトラで高速で飛ぶなど、自分で負荷を増やしている人だけ、リージョンが重い間は描画距離を短くします。", "player-budget"),
            ("RAM ワールド", "ワールドを RAM に置き、ディスクへはバックグラウンドで書き込みます。チャンクの保存や読み込みでディスクを待つことがありません。", "ram-world"),
            ("事前生成", "空いているコアをすべて使って地形を前もって作ります。探索中は、できあがったチャンクを読み込むだけになります。", "pregeneration"),
            ("分担のクライアント", "新しいチャンクのノイズの段階をワーカーに送ります。ワーカーが忙しい・遅い・止まっているときは、自分で生成します。", "offload"),
        ],
        "chunk_t": "新しいチャンクができるまで",
        "chunk_p": "リレーとワーカーを使っている場合に、プレイヤーが一度も生成されていない場所へ歩いていくと何が起きるか。",
        "chunk": [
            ("server", "プレイヤーが生成済みの範囲の端に着き、サーバーは新しいチャンクが必要になります。"),
            ("server", "サーバーが構造物の開始点とバイオームを決めます。これはワールド全体に関わるので、サーバーに残ります。"),
            ("server", "ノイズの段階のために、空きのある接続を選んで依頼を送ります。中身はチャンクの位置、ディメンション、近くの構造物の外形です。"),
            ("relay", "リレーは、このディメンションの確認用チャンクが完全に一致したワーカーのうち、一番空いているものに依頼を渡します。"),
            ("worker", "ワーカーが地形の形・洞窟・帯水層を計算し、ブロックと高さマップを返します。"),
            ("server", "サーバーが返事を検証してから反映します。時間内に返事が来なければ、代わりに自分で生成します。"),
            ("server", "サーバーが地表、洞窟、木、鉱石、光を加え、できあがったチャンクをプレイヤーに送ります。"),
        ],
        "who": {"server": "Storia サーバー", "relay": "Storia Relay", "worker": "Storia Worker"},
        "join_t": "プレイヤーが遊ぶまで",
        "join": [
            ("サーバーリスト", "プレイヤーのクライアントがプロキシのアドレスに ping します。Storia Proxy は、storia-proxy.toml の MOTD に {online} などのプレースホルダーを埋めて返します。"),
            ("ログイン", "プロキシが Mojang でプレイヤーを認証し、try リストの最初のサーバーにつなぎます。"),
            ("フォワーディング", "modern フォワーディングが、プレイヤーの UUID とスキンを、フォワーディング用の秘密鍵で署名して Storia サーバーに渡します。サーバーはこれを信頼できます。"),
            ("プレイ中", "タブリストは毎秒、プレイヤーとネットワークのプレースホルダーで更新されます。参加・退出・移動のメッセージは全員に届きます。"),
            ("サーバーの移動", "プレイヤーが別のサーバーへ移るときは、プロキシが接続を保ったまま移します。サーバーが予期せず止まったときは、そのサーバーのプレイヤーを別のサーバーへ移します。"),
        ],
        "wire_t": "それぞれの接続で流れるもの",
        "wire_h": ["接続", "流れるもの", "保護"],
        "wire": [
            ("プレイヤー ↔ Storia Proxy", "Minecraft のプロトコル。移動、チャット、チャンクなど、ゲームに必要なものすべて。", "Minecraft 自体の暗号化（オンラインモード）。"),
            ("Storia Proxy ↔ Storia サーバー", "同じ Minecraft の通信と、引き継いだプレイヤーの身元。", "フォワーディング用の秘密鍵で署名。サーバーはインターネットに直接公開しないでください。"),
            ("Storia サーバー ↔ Relay・Worker", "行きはチャンクの位置、ディメンション、近くの構造物の外形。帰りは地形のブロックと高さマップ。プレイヤー、チャット、インベントリは一切流れません。", "合言葉から作った鍵で AES-256-GCM。合言葉そのものは送られません。"),
            ("Relay ↔ Worker", "同じ地形の依頼と返事を中継します。", "同じ暗号化で、接続ごとに別の鍵。"),
        ],
        "fail_t": "どれかが止まったら",
        "fail_h": ["止まったもの", "起きること"],
        "fail": [
            ("ワーカー", "処理中の依頼は別のワーカーに回るか、サーバーに戻され、サーバーが自分で生成します。そのチャンクの生成が少し遅れる程度です。"),
            ("リレー", "サーバーはすべての地形を自分で生成し、リレーが戻ると自動で接続し直します。"),
            ("Storia サーバー", "プロキシが、そのサーバーのプレイヤーを try リストの別のサーバーへ移します。ほかのサーバーは動き続けます。"),
            ("プロキシ", "戻るまで、プロキシ経由では参加できません。サーバーとワールドは動き続け、何も失われません。"),
            ("サーバーを動かしているマシン", "RAM ワールドでは、最後の同期（初期設定で 5 分ごと）以降の変更が失われます。サーバーのプロセスだけが落ちた場合は、次の起動時に RAM 上のコピーから復旧します。"),
        ],
        "setups_t": "よくある 4 つの構成",
        "setups_p": "まずは 1 つ目から始めて、サーバーが大きくなったらソフトを足していけます。入れ直す必要はありません。",
        "setups": [
            ("サーバー 1 台", "ほとんどのサーバーはこれで十分。すべて 1 台のマシンで動きます。", ["players", "storia"], "Storia のみ"),
            ("ネットワーク", "複数のゲームモードを 1 つのアドレスで。タブリストやメッセージも共通になります。", ["players", "proxy", "storia×2"], "Storia Proxy + Storia"),
            ("お手伝い付きのサーバー", "探索や事前生成が多いサーバーに、空いているマシンを 1〜2 台足します。", ["players", "storia", "worker×2"], "Storia + Storia Worker"),
            ("フルネットワーク", "多くのサーバーで、出入り自由なワーカーを共有します。", ["players", "proxy", "storia×3", "relay", "worker×N"], "4 つすべて"),
        ],
        "chips": {"players": "Players", "proxy": "Proxy", "storia": "Storia", "worker": "Worker", "relay": "Relay"},
        "req_t": "必要なものの一覧",
        "req_h": ["ソフト", "Java", "メモリ", "ポート", "必要なファイル"],
        "req": [
            ("Storia", "25", "ヒープ ＋ RAM 上のワールド", "25565", "ワールド"),
            ("Storia Proxy", "21 以上", "512 MB ほど", "25565", "なし"),
            ("Storia Worker", "25", "2〜4 GB", "25590（リレーを使うなら不要）", "region・entities・poi を除いたワールドフォルダ"),
            ("Storia Relay", "21 以上", "256 MB ほど", "25590", "なし"),
        ],
        "req_note": "ポートはすべて変更できます。4 つのソフトは、毎回のリリースにそろってダウンロードページに入っています。",
        "cta": "4 つともダウンロード",
    },
}
