"""Text for the "How it works" page (/<lang>/how-it-works/). Rendered by build.py."""

HOW = {
    "en-us": {
        "nav": "How it works",
        "title": "How Storia works",
        "kicker": "Architecture",
        "lede": "Storia is four programs that work together. A single Storia server is a complete Minecraft server; add Storia Proxy "
                "for a network, and Storia Workers with a Storia Relay to run one world on several machines. This page explains what "
                "each one does, where it runs and what travels between them.",
        "diagram_label": "Overview of a Storia Cluster",
        "diagram_desc": [
            "Players connect to Storia Proxy, which listens on port 25565.",
            "Storia Proxy sends each player to the Storia Worker that runs the part of the world they are in, using modern forwarding.",
            "Each worker runs one part of the shared world. When a player crosses into another worker's part, Storia Proxy moves them without a loading screen.",
            "The workers and the proxy connect to Storia Relay, which listens on port 25590, stores the world and decides who runs what. All of it is encrypted.",
        ],
        "d": {"players": "Players", "proxy": "Storia Proxy", "worker": "Worker", "wsub": "part of the world",
              "relay": "Storia Relay", "rsub": "the world · :25590", "net": "Network", "game": "Workers", "help": "Coordinator",
              "mc": "Minecraft · 25565", "fwd": "modern forwarding", "enc": "encrypted", "move": "seamless move"},
        "roles_t": "The four programs",
        "roles_p": "Each program has one job. Together they run one world on as many machines as your players need.",
        "roles": {
            "storia": {
                "role": "The game server",
                "does": "Runs a world: players, mobs, redstone, farms, chunks. Built on Folia, so different areas of the world tick on different CPU cores.",
                "not": "Does not need the other three. On its own it is a complete Minecraft server.",
                "runs": "Your main machine (or one per game mode behind a proxy).",
                "needs": "Java 25, RAM for the world (RAM world) plus the heap.",
                "ports": "25565 for players (or a private port behind the proxy).",
                "config": "storia.yml, plus the usual Paper and Folia files.",
                "docs": "getting-started",
            },
            "proxy": {
                "role": "The front door",
                "does": "Accepts every player on one address and sends them to the right server or worker. In a cluster it switches players between workers without a loading screen. Shows the server list MOTD, a live tab list and network-wide messages, built from 50 placeholders.",
                "not": "Does not run any world, so it needs very little CPU. Plugins for it are Velocity plugins.",
                "runs": "Any small machine, often next to the servers.",
                "needs": "Java 21+, about 512 MB of RAM.",
                "ports": "25565 for players.",
                "config": "velocity.toml, storia-proxy.toml.",
                "docs": "proxy",
            },
            "worker": {
                "role": "One server of a cluster",
                "does": "Runs the part of the shared world where its players are: chunks, mobs, redstone and the players themselves. Add workers when your players outgrow one machine.",
                "not": "Keeps no world of its own: chunks, player data and shared data are read from and written to the relay.",
                "runs": "Any machine that could run a Storia server.",
                "needs": "Java 25, about the CPU and RAM of a normal Storia server. No world copy: it fetches the world settings from the relay.",
                "ports": "25565 for the proxy (keep it private).",
                "config": "storia.yml (cluster.*).",
                "docs": "worker",
            },
            "relay": {
                "role": "The coordinator",
                "does": "Stores the world, gives every part of it to one worker at a time, puts players who meet on the same worker, balances busy workers and tells the proxy when to move a player.",
                "not": "Runs no part of the world itself and needs no Minecraft server.",
                "runs": "One reachable machine with disk space for the world; can be the proxy's machine.",
                "needs": "Java 21+, about 512 MB of RAM, disk for the world.",
                "ports": "25590 for workers and the proxy.",
                "config": "relay.properties.",
                "docs": "relay",
            },
        },
        "labels": {"does": "What it does", "not": "What it does not do", "runs": "Runs on", "needs": "Needs", "ports": "Ports", "config": "Configuration", "docs": "Read the docs"},
        "inside_t": "Inside every Storia server",
        "inside_p": "These layers run in a single Storia server and in every worker of a cluster.",
        "inside": [
            ("Regions", "Folia groups nearby chunks into regions. Each region ticks on its own CPU core, so a busy base on one side of the world does not slow down a player on the other side.", "introduction"),
            ("Tick guard", "When a region gets too slow, mobs in crowded chunks think less often. Players standing there are not limited, and redstone is never touched.", "tick-guard"),
            ("Player budget", "Only players who add load by themselves, such as flying fast with elytra, get a shorter view distance while their region is busy.", "player-budget"),
            ("RAM world", "On a single server, worlds live in RAM and are written to disk in the background, so saving and loading chunks never waits for the disk.", "ram-world"),
            ("Pregeneration", "Generates terrain ahead of time using every spare core, so exploring only loads chunks that already exist.", "pregeneration"),
            ("Cluster client", "In a worker, reads and writes chunks through the relay, keeps writes on disk while the relay is away, and hands players over when they move.", "cluster"),
        ],
        "chunk_t": "The journey of a player between workers",
        "chunk_p": "What happens when Bob, on worker B, flies toward Alice, who is on worker A.",
        "chunk": [
            ("worker", "Every second, each worker tells the relay which parts of the world its players can see."),
            ("relay", "Bob's view is about to touch Alice's area. The relay decides they belong on one worker: the one with more players there, A."),
            ("relay", "The relay asks worker B to hand Bob over. B saves his inventory, advancements, statistics and position, and reports ready."),
            ("proxy", "Storia Proxy connects Bob to worker A in the background with the same entity id, then switches his connection over: no login, no respawn, no loading screen."),
            ("worker", "Worker A reads Bob's data from the relay; the cells B was running are released and A takes them over from their saved state."),
            ("worker", "Bob keeps flying. His client never noticed that the server behind it changed."),
        ],
        "who": {"server": "Storia server", "relay": "Storia Relay", "worker": "Storia Worker", "proxy": "Storia Proxy"},
        "join_t": "The journey of a player",
        "join": [
            ("Server list", "The player's client pings the proxy's address. Storia Proxy answers with the MOTD from storia-proxy.toml, with placeholders such as {online} filled in."),
            ("Login", "The proxy authenticates the player with Mojang. In a cluster it asks the relay which worker runs the place they logged out, and connects them there."),
            ("Forwarding", "Modern forwarding passes the player's UUID and skin to the server, signed with the forwarding secret, so the server can trust it."),
            ("Playing", "The tab list refreshes every second with placeholders about the player and the network. Join, leave and switch messages go to everyone."),
            ("Moving", "Crossing into another worker's part of the world moves the player without a loading screen. Moving to another server of a network (lobby, minigames) is a normal switch."),
        ],
        "wire_t": "What travels over each connection",
        "wire_h": ["Connection", "Carries", "Protection"],
        "wire": [
            ("Player ↔ Storia Proxy", "The Minecraft protocol: movement, chat, chunks, everything the game needs.", "Minecraft's own encryption (online mode)."),
            ("Storia Proxy ↔ Storia server or worker", "The same Minecraft traffic, plus the forwarded player identity.", "Signed with the forwarding secret. Keep servers and workers off the public internet."),
            ("Storia Worker ↔ Storia Relay", "Chunks, entities, player data, advancements, statistics, maps, the scoreboard, and who runs which part of the world.", "AES-256-GCM with keys derived from your shared secret, which is never sent."),
            ("Storia Proxy ↔ Storia Relay", "Which worker a player should join, and when to move a player.", "The same encryption, with its own keys per connection."),
        ],
        "fail_t": "When something stops",
        "fail_h": ["If this stops", "What happens"],
        "fail": [
            ("A worker, with /stop", "It first moves its players to the other workers, then saves and stops. Nobody is kicked."),
            ("A worker that crashes", "The proxy sends its players to another worker. Within 15 seconds the relay gives its part of the world to another worker, from the last saved state."),
            ("The relay", "Workers keep running and keep their writes on disk until it is back. New players cannot join and nobody is moved in the meantime."),
            ("The proxy", "Players cannot join through it until it is back. Servers, workers and their world keep running and nothing is lost."),
            ("A single server's machine", "With the RAM world, changes since the last sync (5 minutes by default) are lost; if only the server process dies, the RAM copy is recovered on the next start."),
        ],
        "setups_t": "Three common setups",
        "setups_p": "Start with the first one and add programs as your server grows.",
        "setups": [
            ("Single server", "For most servers. Everything on one machine.", ["players", "storia"], "Storia only"),
            ("Network", "Several game modes behind one address, with a shared tab list and messages.", ["players", "proxy", "storia×2"], "Storia Proxy + Storia"),
            ("Cluster", "One big world on several machines. Add workers as players grow.", ["players", "proxy", "worker×N", "relay"], "Storia Proxy + Storia Worker + Storia Relay"),
        ],
        "chips": {"players": "Players", "proxy": "Proxy", "storia": "Storia", "worker": "Worker", "relay": "Relay"},
        "req_t": "Requirements at a glance",
        "req_h": ["Program", "Java", "Memory", "Port", "Files it needs"],
        "req": [
            ("Storia", "25", "Heap + the world in RAM", "25565", "The world"),
            ("Storia Proxy", "21+", "~512 MB", "25565", "None"),
            ("Storia Worker", "25", "Like a Storia server", "25565 (private)", "None: fetches the world settings from the relay"),
            ("Storia Relay", "21+", "~512 MB + disk", "25590", "The world"),
        ],
        "req_note": "Every port can be changed. All four programs come in every release on the downloads page.",
        "cta": "Download all four",
    },
    "ja-jp": {
        "nav": "仕組み",
        "title": "Storia の仕組み",
        "kicker": "Architecture",
        "lede": "Storia は、連携して動く 4 つのソフトでできています。Storia サーバー 1 台だけでも完全な Minecraft サーバーです。"
                "Storia Proxy を足せばネットワークに、Storia Worker と Storia Relay を足せば 1 つのワールドを複数のマシンで動かせます。"
                "このページでは、それぞれの役割、動かす場所、やり取りする内容を説明します。",
        "diagram_label": "Storia Cluster の構成図",
        "diagram_desc": [
            "プレイヤーは、Storia Proxy（ポート 25565 で待ち受け）に接続します。",
            "Storia Proxy は、modern フォワーディングを使って、プレイヤーのいる場所を動かしている Storia Worker に送ります。",
            "各ワーカーは共有するワールドの一部を動かします。プレイヤーが別のワーカーの場所に入ると、Storia Proxy が読み込み画面なしで移します。",
            "ワーカーとプロキシは Storia Relay（ポート 25590 で待ち受け）に接続します。Relay はワールドを保管し、どこを誰が動かすかを決めます。通信はすべて暗号化されます。",
        ],
        "d": {"players": "Players", "proxy": "Storia Proxy", "worker": "Worker", "wsub": "part of the world",
              "relay": "Storia Relay", "rsub": "the world · :25590", "net": "Network", "game": "Workers", "help": "Coordinator",
              "mc": "Minecraft · 25565", "fwd": "modern forwarding", "enc": "encrypted", "move": "seamless move"},
        "roles_t": "4 つのソフト",
        "roles_p": "それぞれに 1 つの役割があります。組み合わせると、1 つのワールドを、プレイヤーの数に合わせて何台ものマシンで動かせます。",
        "roles": {
            "storia": {
                "role": "ゲームサーバー",
                "does": "ワールドを動かします。プレイヤー、モブ、回路、トラップ、チャンクのすべてです。Folia ベースなので、ワールドの場所ごとに別々の CPU コアで処理します。",
                "not": "ほかの 3 つは必要ありません。単体で完全な Minecraft サーバーです。",
                "runs": "メインのマシン（プロキシを使うなら、ゲームモードごとに 1 台ずつ）。",
                "needs": "Java 25。RAM ワールドのためのワールド分の RAM と、ヒープ。",
                "ports": "プレイヤー用の 25565（プロキシの裏に置くなら非公開のポート）。",
                "config": "storia.yml と、いつもの Paper・Folia の設定ファイル。",
                "docs": "getting-started",
            },
            "proxy": {
                "role": "玄関",
                "does": "すべてのプレイヤーを 1 つのアドレスで受け付け、適切なサーバーやワーカーに送ります。Cluster では、読み込み画面なしでワーカー間を移します。サーバーリストの MOTD、自動更新のタブリスト、ネットワーク全体のメッセージを、50 個のプレースホルダーで表示します。",
                "not": "ワールドを動かさないので、CPU はほとんど使いません。プラグインは Velocity 用のものを使います。",
                "runs": "小さなマシンで十分。サーバーと同じ場所に置くことが多いです。",
                "needs": "Java 21 以上。RAM 512 MB ほど。",
                "ports": "プレイヤー用の 25565。",
                "config": "velocity.toml、storia-proxy.toml。",
                "docs": "proxy",
            },
            "worker": {
                "role": "Cluster のサーバー 1 台",
                "does": "共有するワールドのうち、自分のプレイヤーがいる場所（チャンク・モブ・回路・プレイヤー）を動かします。プレイヤーが 1 台に収まらなくなったら、ワーカーを足します。",
                "not": "自分のワールドは持ちません。チャンク・プレイヤーデータ・共有データは Relay から読み書きします。",
                "runs": "Storia サーバーを動かせるマシンならどれでも。",
                "needs": "Java 25。普通の Storia サーバーと同じくらいの CPU と RAM。ワールドのコピーは不要（Relay から設定を取り寄せます）。",
                "ports": "プロキシ用の 25565（非公開に）。",
                "config": "storia.yml（cluster.*）。",
                "docs": "worker",
            },
            "relay": {
                "role": "まとめ役",
                "does": "ワールドを保管し、場所ごとに動かすワーカーを 1 台ずつ決め、近づいたプレイヤーを同じワーカーにまとめ、忙しいワーカーの仕事を分け、プレイヤーを移すタイミングをプロキシに伝えます。",
                "not": "ワールドのどこも自分では動かさず、Minecraft サーバーも要りません。",
                "runs": "ワールド分のディスクがある、届く場所のマシン 1 台。プロキシと同じマシンでも構いません。",
                "needs": "Java 21 以上。RAM 512 MB ほどと、ワールド分のディスク。",
                "ports": "ワーカーとプロキシ用の 25590。",
                "config": "relay.properties。",
                "docs": "relay",
            },
        },
        "labels": {"does": "役割", "not": "しないこと", "runs": "動かす場所", "needs": "必要なもの", "ports": "ポート", "config": "設定", "docs": "ドキュメントを読む"},
        "inside_t": "どの Storia サーバーにも入っているもの",
        "inside_p": "次の仕組みは、Storia サーバー単体でも、Cluster の各ワーカーでも動きます。",
        "inside": [
            ("リージョン", "Folia は近くのチャンクをリージョンにまとめ、リージョンごとに別々の CPU コアで処理します。ワールドの片側の重い拠点が、反対側のプレイヤーを遅くすることはありません。", "introduction"),
            ("Tick Guard", "リージョンが重くなりすぎると、密集チャンクのモブの判断の回数を減らします。そこにいるプレイヤーは制限されず、回路にも触れません。", "tick-guard"),
            ("プレイヤーごとの予算", "エリトラで高速で飛ぶなど、自分で負荷を増やしている人だけ、リージョンが重い間は描画距離を短くします。", "player-budget"),
            ("RAM ワールド", "単体のサーバーでは、ワールドを RAM に置き、ディスクへはバックグラウンドで書き込みます。チャンクの保存や読み込みでディスクを待つことがありません。", "ram-world"),
            ("事前生成", "空いているコアをすべて使って地形を前もって作ります。探索中は、できあがったチャンクを読み込むだけになります。", "pregeneration"),
            ("Cluster のクライアント", "ワーカーでは、チャンクを Relay 経由で読み書きし、Relay が止まっている間は書き込みをディスクで待たせ、移動するプレイヤーを引き渡します。", "cluster"),
        ],
        "chunk_t": "ワーカー間を移動するまで",
        "chunk_p": "ワーカー B にいる Bob が、ワーカー A にいる Alice の方へ飛んでいったときに起きること。",
        "chunk": [
            ("worker", "各ワーカーは毎秒、プレイヤーに見えている場所を Relay に報告します。"),
            ("relay", "Bob の見える範囲が Alice のエリアに触れそうになります。Relay は 2 人を同じワーカーにまとめると決めます。その場所のプレイヤーが多い A です。"),
            ("relay", "Relay はワーカー B に Bob の引き渡しを頼みます。B はインベントリ・進捗・統計・位置を保存し、準備完了を伝えます。"),
            ("proxy", "Storia Proxy は裏で Bob を同じエンティティ ID のままワーカー A につなぎ、接続を切り替えます。ログインし直しも、再スポーンも、読み込み画面もありません。"),
            ("worker", "ワーカー A は Bob のデータを Relay から読み込みます。B が動かしていたセルは解放され、A が保存された状態から引き継ぎます。"),
            ("worker", "Bob はそのまま飛び続けます。クライアントは、裏のサーバーが変わったことに気づきません。"),
        ],
        "who": {"server": "Storia サーバー", "relay": "Storia Relay", "worker": "Storia Worker", "proxy": "Storia Proxy"},
        "join_t": "プレイヤーが遊ぶまで",
        "join": [
            ("サーバーリスト", "プレイヤーのクライアントがプロキシのアドレスに ping します。Storia Proxy は、storia-proxy.toml の MOTD に {online} などのプレースホルダーを埋めて返します。"),
            ("ログイン", "プロキシが Mojang でプレイヤーを認証します。Cluster では、ログアウトした場所を動かしているワーカーを Relay に聞き、そこにつなぎます。"),
            ("フォワーディング", "modern フォワーディングが、プレイヤーの UUID とスキンを、フォワーディング用の秘密鍵で署名してサーバーに渡します。サーバーはこれを信頼できます。"),
            ("プレイ中", "タブリストは毎秒、プレイヤーとネットワークのプレースホルダーで更新されます。参加・退出・移動のメッセージは全員に届きます。"),
            ("移動", "別のワーカーの場所に入ると、読み込み画面なしで移ります。ネットワーク内の別のサーバー（ロビーやミニゲーム）への移動は、普通のサーバー移動です。"),
        ],
        "wire_t": "それぞれの接続で流れるもの",
        "wire_h": ["接続", "流れるもの", "保護"],
        "wire": [
            ("プレイヤー ↔ Storia Proxy", "Minecraft のプロトコル。移動、チャット、チャンクなど、ゲームに必要なものすべて。", "Minecraft 自体の暗号化（オンラインモード）。"),
            ("Storia Proxy ↔ Storia サーバー・ワーカー", "同じ Minecraft の通信と、引き継いだプレイヤーの身元。", "フォワーディング用の秘密鍵で署名。サーバーとワーカーはインターネットに直接公開しないでください。"),
            ("Storia Worker ↔ Storia Relay", "チャンク、エンティティ、プレイヤーデータ、進捗、統計、地図、スコアボード、そしてどこを誰が動かすか。", "合言葉から作った鍵で AES-256-GCM。合言葉そのものは送られません。"),
            ("Storia Proxy ↔ Storia Relay", "プレイヤーをどのワーカーに入れるか、いつ移すか。", "同じ暗号化。接続ごとに別の鍵を使います。"),
        ],
        "fail_t": "何かが止まったとき",
        "fail_h": ["止まったもの", "どうなるか"],
        "fail": [
            ("ワーカー（/stop）", "先にプレイヤーをほかのワーカーへ移してから、保存して止まります。キックされる人はいません。"),
            ("落ちたワーカー", "プロキシがそのプレイヤーを別のワーカーへ送ります。15 秒以内に、Relay がその場所を最後に保存された状態から別のワーカーに任せます。"),
            ("Relay", "ワーカーは動き続け、戻るまで書き込みをディスクで待たせます。その間、新しいプレイヤーは入れず、移動も起きません。"),
            ("プロキシ", "戻るまで、プロキシ経由では入れません。サーバー・ワーカーとワールドは動き続け、何も失われません。"),
            ("単体サーバーのマシン", "RAM ワールドでは、最後の同期（初期設定で 5 分ごと）以降の変更が失われます。サーバーのプロセスだけが落ちた場合は、次の起動時に RAM 上のコピーから復旧します。"),
        ],
        "setups_t": "よくある 3 つの構成",
        "setups_p": "まずは 1 つ目から始めて、サーバーの成長に合わせてソフトを足していけます。",
        "setups": [
            ("単体のサーバー", "ほとんどのサーバーはこれで十分です。すべて 1 台のマシンで動かします。", ["players", "storia"], "Storia のみ"),
            ("ネットワーク", "複数のゲームモードを 1 つのアドレスで。タブリストとメッセージは共通です。", ["players", "proxy", "storia×2"], "Storia Proxy ＋ Storia"),
            ("Cluster", "1 つの大きなワールドを複数のマシンで。プレイヤーが増えたらワーカーを足します。", ["players", "proxy", "worker×N", "relay"], "Storia Proxy ＋ Storia Worker ＋ Storia Relay"),
        ],
        "chips": {"players": "Players", "proxy": "Proxy", "storia": "Storia", "worker": "Worker", "relay": "Relay"},
        "req_t": "必要なもの一覧",
        "req_h": ["ソフト", "Java", "メモリ", "ポート", "必要なファイル"],
        "req": [
            ("Storia", "25", "ヒープ ＋ RAM 上のワールド", "25565", "ワールド"),
            ("Storia Proxy", "21 以上", "512 MB ほど", "25565", "なし"),
            ("Storia Worker", "25", "Storia サーバーと同じくらい", "25565（非公開）", "なし（Relay からワールドの設定を取り寄せる）"),
            ("Storia Relay", "21 以上", "512 MB ほど ＋ ディスク", "25590", "ワールド"),
        ],
        "req_note": "ポートはすべて変更できます。4 つのソフトは、ダウンロードページのすべてのリリースに入っています。",
        "cta": "4 つともダウンロード",
    },
}
